### ISSUE TITLE
Constant restarts on docker container

### ISSUE THREAD

**Issue by charliwest** [clambin/tado-exporter#170]
Hello, me again! Happy new year.

I am getting constant restarts on the container and these logs:-

```
2024-01-04T11:35:00.132193264Z github.com/spf13/cobra.(*Command).Execute(...)
2024-01-04T11:35:00.132236312Z 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
2024-01-04T11:35:00.132463987Z main.main()
2024-01-04T11:35:00.132509647Z 	/home/runner/work/tado-exporter/tado-exporter/cmd/tado-monitor/tado-monitor.go:29 +0x1a
2024-01-04T11:36:03.283525839Z 2024-01-04T12:36:03.283294564+01:00 INFO msg=tado-monitor starting version=v0.14.2
2024-01-04T11:36:03.668824347Z 2024-01-04T12:36:03.668628055+01:00 WARN msg=no rules found. controller will not run
2024-01-04T11:36:03.670881457Z panic: runtime error: invalid memory address or nil pointer dereference
2024-01-04T11:36:03.670980945Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x97fc38]
2024-01-04T11:36:03.671043002Z 
2024-01-04T11:36:03.671082255Z goroutine 1 [running]:
2024-01-04T11:36:03.671134905Z github.com/clambin/tado-exporter/internal/app.makeTasks(0xc0005c6d00?, 0x1042b80?, {0x0, 0x0, 0x0}, {0xbf1968, 0x7}, 0x0?)
2024-01-04T11:36:03.671194254Z 	/home/runner/work/tado-exporter/tado-exporter/internal/app/app.go:103 +0xb18
2024-01-04T11:36:03.671266881Z github.com/clambin/tado-exporter/internal/app.New(0xc00020a000, {0xbf1968, 0x7}, 0x0?)
2024-01-04T11:36:03.671314678Z 	/home/runner/work/tado-exporter/tado-exporter/internal/app/app.go:40 +0x1ce
2024-01-04T11:36:03.671362212Z main.Main(0x100c460, {0xafa692?, 0x7?, 0xaf98d5?})
2024-01-04T11:36:03.671407691Z 	/home/runner/work/tado-exporter/tado-exporter/cmd/tado-monitor/tado-monitor.go:44 +0x274
2024-01-04T11:36:03.671457386Z github.com/spf13/cobra.(*Command).execute(0x100c460, {0xc000122050, 0x0, 0x0})
2024-01-04T11:36:03.671505902Z 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
2024-01-04T11:36:03.671558950Z github.com/spf13/cobra.(*Command).ExecuteC(0x100c460)
2024-01-04T11:36:03.671603821Z 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
2024-01-04T11:36:03.671653061Z github.com/spf13/cobra.(*Command).Execute(...)
2024-01-04T11:36:03.671703733Z 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
2024-01-04T11:36:03.671752119Z main.main()
2024-01-04T11:36:03.671817588Z 	/home/runner/work/tado-exporter/tado-exporter/cmd/tado-monitor/tado-monitor.go:29 +0x1a
```
Any idea what the issue could be?

**Comment by clambin** [comment]
fixed in 0.14.3:  wasn't taking into account the scenario where no rules have been defined.

**Comment by charliwest** [comment]
Thanks a lot for the quick fix, works again for me now.
I only use for export at the moment.
Thanks again for the great work on this!

**Comment by charliwest** [comment]
Thanks a lot for the quick fix, works again for me now.
I only use for export at the moment.
Thanks again for the great work on this!
